### ISSUE TITLE
What's courseDataGz?

### ISSUE THREAD

**Issue by Seil0** [Tarnadas/smmdb#1]
http://smmdb.ddns.net/api/getcourses?prettify=1&ids=5972237ff160681a439d9956
is providing an attribute called "courseDataGz" which is a huge item.
This breaks my smmdb integration in my application, so i want to ask what's that and is there any way to work around?

**Comment by Tarnadas** [comment]
Oh that should not be displayed. it's the course itself serialized and gzipped. I am currently moving the server and that part is happening, because I got a database error while trying to import a lot of files into the database.
Once I deployed to the new server, it should no longer be displayed.
For now you can use the `filter` option for requests
http://smmdb.ddns.net/api/getcourses?prettify=1&ids=5972237ff160681a439d9956&filter=id,title,maker

**Comment by Tarnadas** [comment]
This is happening, because I accidentally tried to move a lot of files into the database and had no more disk space available on my VPS. I am currently moving the server to another location. Once this happened, it will no longer be displayed, because I made several commits and the current server is not receiving them.

As a workaround you can use the `filter` option:

http://smmdb.ddns.net/api/getcourses?prettify=1&ids=5972237ff160681a439d9956&filter=id,title,owner,difficulty,videoid,lastmodified,uploaded,maker,gameStyle,courseTheme,courseThemeSub,time,autoScroll,autoScrollSub,width,widthSub,stars,vFull,vPrev

**Comment by Tarnadas** [comment]
This can be closed, because I just deployed and updated on another server. You can do a regular `getcourses` API call without the filter option
